### ISSUE TITLE
io modules does not collect stats for /dev/vda

### ISSUE THREAD

**Issue by lickdragon** [ganglia/ganglia-modules-linux#4]
Hi,
   ganglia-modules-linux does not collect drive iostats from /dev/vd* devices.  These are found in KVM VMs (at least when installed with Debian or Scientific Linux 6).
   It looks like possibly the reason vd* are not included is because their major number is not the same as a physical hard drive.
   On SL6, the major number is 252, and in Debian, the major number is 254 (boo!)

It looks like KVM virtual drives don't have an official major number.
https://www.kernel.org/doc/Documentation/devices.txt
240-254 block	LOCAL/EXPERIMENTAL USE
		Allocated for local/experimental use.  For devices not
		assigned official numbers, these ranges should be
		used in order to avoid conflicting with future assignments.

This is part of the code in mod_io.c that makes me think the major number is important:
#define SCSI_DISK_MAJOR(M) ((M) == SCSI_DISK0_MAJOR || \
((M) >= SCSI_DISK1_MAJOR && \
(M) <= SCSI_DISK7_MAJOR) || \
((M) >= SCSI_DISK8_MAJOR && \
(M) <= SCSI_DISK15_MAJOR))
#endif /* !SCSI_DISK_MAJOR */

Thanks for your help!
C.

**Comment by dpocock** [comment]
I don't have a KVM environment to test this and I can't work on this immediately anyway.

Could you please have a look at the code and maybe submit a pull request?

Any support for non-standard things should be configurable, not hard coded.

**Comment by hawson** [comment]
I expect that /dev/xvd? devices aren't tracked either.  They have major number 202.

    % ls -l /dev/xvd?
    brw-rw---- 1 root disk 202,  0 Mar 10 20:50 /dev/xvda
    brw-rw---- 1 root disk 202, 16 Mar 10 20:50 /dev/xvdb
    brw-rw---- 1 root disk 202, 32 Mar 10 20:50 /dev/xvdc
    brw-rw---- 1 root disk 202, 48 Mar 10 20:50 /dev/xvdd
    brw-rw---- 1 root disk 202, 64 Mar 10 20:50 /dev/xvde

**Comment by cwseys** [comment]
Thanks!
